# Generated by Django 3.1 on 2020-08-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200810_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='customer_profile_pic',
            field=models.ImageField(blank=True, default='AVATAR.png', null=True, upload_to=''),
        ),
    ]
